remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
title: Daphne Schlesinger
logo: rle_headshot.jpg
description:
lang: en_US
email: daphneschles@gmail.com
url: https://daphneschlesinger.com/
author:
  name: Daphne Schlesinger
  picture: rle_headshot.jpg
github_username: daphneschles
